name: Deploy to hosted server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Build static bundle
              run: npm run build
            - name: Copy to server
              env:
                  HOST: ${{ secrets.DEPLOY_HOST }}
                  PORT: ${{ secrets.DEPLOY_PORT }}
                  SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
              run: |
                  echo "$SSH_KEY" > keyfile
                  chmod 400 keyfile
                  mkdir ~/.ssh
                  ssh-keyscan -H $HOST > ~/.ssh/known_hosts
                  rsync --perms --chmod=755 -e "ssh -p $PORT -i keyfile" -r build/ nclifford@$HOST:~/html/spotify-data-viewer
