name: Deploy to hosted server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Build static bundle
              run: npm run build
            - name: Fix permissions
              run: chmod -R 755 build
            - name: Copy to server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  port: ${{ secrets.DEPLOY_PORT }}
                  username: nclifford
                  key: ${{ secrets.DEPLOY_SSH_KEY }}
                  target: ~/html/spotify-data-viewer
                  source: ./build/*
                  strip_components: 1
