name: Deploy to hosted server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Build static bundle
              run: npm run build
            - name: Copy to server
              env:
                  HOST: ${{ secrets.DEPLOY_HOST }}
                  PORT: ${{ secrets.DEPLOY_PORT }}
                  KEY: ${{ secrets.DEPLOY_SSH_KEY }}
              run: |
                  echo "$DEPLOY_SSH_KEY" > keyfile
                  scp -i keyfile -P $PORT -r build/* nclifford@$HOST:~/spotify-data-viewer
                  ssh -i keyfile -P $PORT nclifford@$HOST "chmod -R 755 ~spotify-data-viewer"
